url: https://realms-team.github.io
baseurl: 

# Site settings
title: REALMS
email: thomas.watteyne@inria.fr
description: "Real-Time Real-World Monitoring Systems. Associate research team between Inria, UC Berkeley and the University of Michigan"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Thomas Watteyne
  pic: thomas_watteyne
  position: co-PI
  social:
    - title: globe
      url: https://twatteyne.wordpress.com/
    - title: linkedin
      url: https://fr.linkedin.com/in/thomaswatteyne
    - title: github
      url: https://github.com/twatteyne
    - title: bitbucket
      url: https://bitbucket.org/twatteyne/profile/activity

- name: Steven Glaser
  pic: steven_glaser
  position: co-PI
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Branko Kerkez
  pic: branko_kerkez
  position: co-PI
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
